-- =====================================================================
-- Cool Pizza – dane startowe (menu z coolpizza.pl / Appinet, stan 06.10.2026)
-- Uruchom JEDEN raz po schema.sql. Potem wszystko zmieniasz w panelu admina.
-- =====================================================================
begin;
insert into lokale (id, nazwa, adres, telefon, email, godz_od, godz_do, kolejnosc) values
  (5, 'COOL PIZZA Ostrów Wielkopolski', 'ul. Śmigielskiego 20, 63-400 Ostrów Wielkopolski', '62 307 07 07', 'kontakt@coolpizza.pl', '11:00', '23:00', 1),
  (2, 'COOL PIZZA Kalisz', 'Plac Świętego Józefa 8, 62-800 Kalisz', '794 254 713', 'kontakt@coolpizza.pl', '11:00', '23:00', 2)
on conflict (id) do nothing;

insert into kategorie (nazwa, kolejnosc) values ('Pizza',1),('Zestawy',2),('Promocje',3),('Napoje',4),('Sosy',5) on conflict do nothing;
insert into rozmiary (nazwa, kolejnosc, opakowanie) values ('30 cm',1,0),('40 cm',2,0),('50 cm',3,0),('60 cm',4,0) on conflict do nothing;

insert into produkty (kategoria_id, nazwa, opis, tagi, dodatki, sos_gratis, kolejnosc) values
  ((select id from kategorie where nazwa='Pizza'), 'MARGHERITA', 'sos pomidorowy, ser, oregano', '{wege}', true, 1, 1),
  ((select id from kategorie where nazwa='Pizza'), 'COOL-PIZZA', 'sos pomidorowy, ser, mięso mielone, świeży ogórek, pieczarki, cebula, oregano', '{}', true, 1, 2),
  ((select id from kategorie where nazwa='Pizza'), 'CLASIC', 'sos pomidorowy, ser, salami, pieczarki, szynka, oregano', '{}', true, 1, 3),
  ((select id from kategorie where nazwa='Pizza'), 'VESUWIO', 'sos pomidorowy, ser, salami, pieczarki, papryka konserwowa, oregano', '{}', true, 1, 4),
  ((select id from kategorie where nazwa='Pizza'), 'HAWANA', 'sos pomidorowy, ser, szynka, oregano, ananas', '{}', true, 1, 5),
  ((select id from kategorie where nazwa='Pizza'), 'GIOWANI', 'sos pomidorowy, ser, boczek, cebula, oliwki zielone, ogórek konserwowy, oregano', '{}', true, 1, 6),
  ((select id from kategorie where nazwa='Pizza'), 'ANGELA', 'sos pomidorowy, ser, polędwica, groszek, jajko, cebula, oregano', '{}', true, 1, 7),
  ((select id from kategorie where nazwa='Pizza'), 'DESPERADO', 'sos pomidorowy, ser, pieczarki, papryka jalapeno, salami, czosnek, oregano', '{ostra}', true, 1, 8),
  ((select id from kategorie where nazwa='Pizza'), 'VEGETARIANA', 'sos pomidorowy, ser, pieczarki, cebula, pomidor, papryka konserwowa, oregano', '{wege}', true, 1, 9),
  ((select id from kategorie where nazwa='Pizza'), 'SPECJAL', 'sos pomidorowy, ser, pieczarki, kukurydza, szynka, ananas, oregano', '{}', true, 1, 10),
  ((select id from kategorie where nazwa='Pizza'), 'KOLUMB', 'sos pomidorowy, ser, szynka, papryka konserwowa, pieczarki, oregano', '{}', true, 1, 11),
  ((select id from kategorie where nazwa='Pizza'), 'ROMANA', 'sos pomidorowy, ser, kurczak panierowany, cebula, groszek, oregano', '{}', true, 1, 12),
  ((select id from kategorie where nazwa='Pizza'), 'CZIKEN', 'sos pomidorowy, ser, kurczak panierowany, papryka jalapeno, ananas, oregano', '{ostra}', true, 1, 13),
  ((select id from kategorie where nazwa='Pizza'), 'GRECKA', 'sos pomidorowy, ser, salami, szpinak, ser feta, oregano', '{}', true, 1, 14),
  ((select id from kategorie where nazwa='Pizza'), 'CARBONARA', 'sos śmietanowy, ser, cebula, boczek, bazylia, oregano', '{}', true, 1, 15),
  ((select id from kategorie where nazwa='Pizza'), 'MARCO POLO', 'sos pomidorowy, ser, pieczarki, czosnek, salami, papryka konserwowa, szpinak, oregano', '{}', true, 1, 16),
  ((select id from kategorie where nazwa='Pizza'), 'NAPOLI', 'sos pomidorowy, ser, tuńczyk, cebula, ogórek konserwowy, oliwki zielone, jajko, oregano', '{ryba}', true, 1, 17),
  ((select id from kategorie where nazwa='Pizza'), 'SZPARAGOWA', 'sos pomidorowy, ser, szparagi, ser grana padano, szynka dojrzewająca, oregano', '{}', true, 1, 18),
  ((select id from kategorie where nazwa='Pizza'), 'SORENTO', 'sos pomidorowy, ser, polędwica, kapary, pomidor, cebula, oregano', '{}', true, 1, 19),
  ((select id from kategorie where nazwa='Pizza'), 'PYRA PIZZA', 'sos pomidorowy, ser, boczek, cebula, ziemniaki, oregano', '{}', true, 1, 20),
  ((select id from kategorie where nazwa='Pizza'), 'MARSJAŃSKA', 'sos pomidorowy, ser, anchois, ananas, oregano', '{ryba}', true, 1, 21),
  ((select id from kategorie where nazwa='Pizza'), 'WIEJSKA', 'sos pomidorowy, ser, salami, boczek, ogórek konserwowy, cebula, jajko, oregano', '{}', true, 1, 22),
  ((select id from kategorie where nazwa='Pizza'), 'CHŁOPSKA', 'sos pomidorowy, ser, salami, pieczarki, boczek, papryka konserwowa, oregano', '{}', true, 1, 23),
  ((select id from kategorie where nazwa='Pizza'), 'GÓRALSKA', 'sos pomidorowy, ser, boczek, cebula, żurawina, ser wędzony, oregano', '{}', true, 1, 24),
  ((select id from kategorie where nazwa='Pizza'), 'SZEFA', 'sos pomidorowy, ser, szynka, cebula, pieczarki, ogórek konserwowy, oregano', '{}', true, 1, 25),
  ((select id from kategorie where nazwa='Pizza'), 'BROKUŁOWA', 'sos pomidorowy, ser, brokuły, cebula, papryka świeża, pomidor, mięso mielone, oregano', '{}', true, 1, 26),
  ((select id from kategorie where nazwa='Pizza'), 'SUSHI PIZZA', 'sos śmietanowy, ser, łosoś wędzony, świeży ogórek, ser philadelphia, liście nori, oregano', '{ryba}', true, 1, 27),
  ((select id from kategorie where nazwa='Pizza'), 'KEBAB PIZZA', 'sos pomidorowy, ser, kebab drobiowy, ogórek konserwowy, pieczarki, cebula, oregano', '{}', true, 1, 28),
  ((select id from kategorie where nazwa='Pizza'), 'NOWA KEBAB PIZZA', 'sos pomidorowy, ser, kebab drobiowy, cebula, ser favita, oregano', '{}', true, 1, 29),
  ((select id from kategorie where nazwa='Pizza'), 'FANTAZJA', 'sos pomidorowy, ser, pomidor, cebula, świeży ogórek, pieczarki, kolby kukurydzy, pieprz, oregano', '{wege}', true, 1, 30),
  ((select id from kategorie where nazwa='Pizza'), 'AMIGOS', 'sos pomidorowy, ser, fasola czerwona, mięso mielone, cebula, kukurydza, płatki chili, oregano', '{ostra}', true, 1, 31),
  ((select id from kategorie where nazwa='Pizza'), 'FRUTTI DI MARE', 'sos pomidorowy, ser, krewetki, rukola, ser grana padano, płatki chili, oregano', '{ostra}', true, 1, 32),
  ((select id from kategorie where nazwa='Pizza'), 'PARMEŃSKA', 'sos pomidorowy, ser, ser grana padano, pomidory suszone, szynka dojrzewająca, rukola, oregano', '{}', true, 1, 33),
  ((select id from kategorie where nazwa='Pizza'), 'Z GRUSZKĄ', 'sos pomidorowy, ser, gruszka, ser lazur, rukola, miód, orzech włoski, oregano', '{wege}', true, 1, 34),
  ((select id from kategorie where nazwa='Pizza'), 'FAMILIJNA', 'sos pomidorowy, ser, polędwica, kabanosy, frankfurterki, salami, papryka konserwowa, oregano', '{}', true, 1, 35),
  ((select id from kategorie where nazwa='Pizza'), 'SEROWA', 'sos pomidorowy, ser feta, ser lazur, ser camembert, pomidor, oregano', '{wege}', true, 1, 36),
  ((select id from kategorie where nazwa='Pizza'), 'VEGE-MARGHERITA', 'sos pomidorowy, ser wegański, oregano', '{wege}', true, 1, 37),
  ((select id from kategorie where nazwa='Pizza'), 'VEGE-RUCOLA', 'sos pomidorowy, ser wegański, rukola, cebula, papryka świeża, pomidor, oliwki zielone, oregano', '{wege}', true, 1, 38),
  ((select id from kategorie where nazwa='Pizza'), 'TWOJA PIZZA', 'sos pomidorowy, ser, oregano', '{}', true, 1, 39)
on conflict do nothing;

insert into ceny (produkt_id, rozmiar_id, cena) values
  ((select id from produkty where nazwa='MARGHERITA'), (select id from rozmiary where nazwa='30 cm'), 30.50),
  ((select id from produkty where nazwa='MARGHERITA'), (select id from rozmiary where nazwa='40 cm'), 48.50),
  ((select id from produkty where nazwa='MARGHERITA'), (select id from rozmiary where nazwa='50 cm'), 64.00),
  ((select id from produkty where nazwa='MARGHERITA'), (select id from rozmiary where nazwa='60 cm'), 75.50),
  ((select id from produkty where nazwa='COOL-PIZZA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='COOL-PIZZA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='COOL-PIZZA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='COOL-PIZZA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='CLASIC'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='CLASIC'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='CLASIC'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='CLASIC'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='VESUWIO'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='VESUWIO'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='VESUWIO'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='VESUWIO'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='HAWANA'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='HAWANA'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='HAWANA'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='HAWANA'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='GIOWANI'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='GIOWANI'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='GIOWANI'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='GIOWANI'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='ANGELA'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='ANGELA'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='ANGELA'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='ANGELA'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='DESPERADO'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='DESPERADO'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='DESPERADO'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='DESPERADO'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='VEGETARIANA'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='VEGETARIANA'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='VEGETARIANA'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='VEGETARIANA'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='SPECJAL'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='SPECJAL'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='SPECJAL'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='SPECJAL'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='KOLUMB'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='KOLUMB'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='KOLUMB'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='KOLUMB'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='ROMANA'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='ROMANA'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='ROMANA'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='ROMANA'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='CZIKEN'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='CZIKEN'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='CZIKEN'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='CZIKEN'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='GRECKA'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='GRECKA'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='GRECKA'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='GRECKA'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='CARBONARA'), (select id from rozmiary where nazwa='30 cm'), 38.50),
  ((select id from produkty where nazwa='CARBONARA'), (select id from rozmiary where nazwa='40 cm'), 59.00),
  ((select id from produkty where nazwa='CARBONARA'), (select id from rozmiary where nazwa='50 cm'), 75.00),
  ((select id from produkty where nazwa='CARBONARA'), (select id from rozmiary where nazwa='60 cm'), 92.00),
  ((select id from produkty where nazwa='MARCO POLO'), (select id from rozmiary where nazwa='30 cm'), 40.00),
  ((select id from produkty where nazwa='MARCO POLO'), (select id from rozmiary where nazwa='40 cm'), 60.50),
  ((select id from produkty where nazwa='MARCO POLO'), (select id from rozmiary where nazwa='50 cm'), 77.00),
  ((select id from produkty where nazwa='MARCO POLO'), (select id from rozmiary where nazwa='60 cm'), 95.00),
  ((select id from produkty where nazwa='NAPOLI'), (select id from rozmiary where nazwa='30 cm'), 40.00),
  ((select id from produkty where nazwa='NAPOLI'), (select id from rozmiary where nazwa='40 cm'), 60.50),
  ((select id from produkty where nazwa='NAPOLI'), (select id from rozmiary where nazwa='50 cm'), 77.00),
  ((select id from produkty where nazwa='NAPOLI'), (select id from rozmiary where nazwa='60 cm'), 95.00),
  ((select id from produkty where nazwa='SZPARAGOWA'), (select id from rozmiary where nazwa='30 cm'), 40.00),
  ((select id from produkty where nazwa='SZPARAGOWA'), (select id from rozmiary where nazwa='40 cm'), 60.50),
  ((select id from produkty where nazwa='SZPARAGOWA'), (select id from rozmiary where nazwa='50 cm'), 77.00),
  ((select id from produkty where nazwa='SZPARAGOWA'), (select id from rozmiary where nazwa='60 cm'), 95.00),
  ((select id from produkty where nazwa='SORENTO'), (select id from rozmiary where nazwa='30 cm'), 40.00),
  ((select id from produkty where nazwa='SORENTO'), (select id from rozmiary where nazwa='40 cm'), 60.50),
  ((select id from produkty where nazwa='SORENTO'), (select id from rozmiary where nazwa='50 cm'), 77.00),
  ((select id from produkty where nazwa='SORENTO'), (select id from rozmiary where nazwa='60 cm'), 95.00),
  ((select id from produkty where nazwa='PYRA PIZZA'), (select id from rozmiary where nazwa='30 cm'), 40.00),
  ((select id from produkty where nazwa='PYRA PIZZA'), (select id from rozmiary where nazwa='40 cm'), 60.50),
  ((select id from produkty where nazwa='PYRA PIZZA'), (select id from rozmiary where nazwa='50 cm'), 77.00),
  ((select id from produkty where nazwa='PYRA PIZZA'), (select id from rozmiary where nazwa='60 cm'), 95.00),
  ((select id from produkty where nazwa='MARSJAŃSKA'), (select id from rozmiary where nazwa='30 cm'), 40.00),
  ((select id from produkty where nazwa='MARSJAŃSKA'), (select id from rozmiary where nazwa='40 cm'), 60.50),
  ((select id from produkty where nazwa='MARSJAŃSKA'), (select id from rozmiary where nazwa='50 cm'), 77.00),
  ((select id from produkty where nazwa='MARSJAŃSKA'), (select id from rozmiary where nazwa='60 cm'), 95.00),
  ((select id from produkty where nazwa='WIEJSKA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='WIEJSKA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='WIEJSKA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='WIEJSKA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='CHŁOPSKA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='CHŁOPSKA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='CHŁOPSKA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='CHŁOPSKA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='GÓRALSKA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='GÓRALSKA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='GÓRALSKA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='GÓRALSKA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='SZEFA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='SZEFA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='SZEFA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='SZEFA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='BROKUŁOWA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='BROKUŁOWA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='BROKUŁOWA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='BROKUŁOWA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='SUSHI PIZZA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='SUSHI PIZZA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='SUSHI PIZZA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='SUSHI PIZZA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='KEBAB PIZZA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='KEBAB PIZZA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='KEBAB PIZZA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='KEBAB PIZZA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='NOWA KEBAB PIZZA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='NOWA KEBAB PIZZA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='NOWA KEBAB PIZZA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='NOWA KEBAB PIZZA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='FANTAZJA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='FANTAZJA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='FANTAZJA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='FANTAZJA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='AMIGOS'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='AMIGOS'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='AMIGOS'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='AMIGOS'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='FRUTTI DI MARE'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='FRUTTI DI MARE'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='FRUTTI DI MARE'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='FRUTTI DI MARE'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='PARMEŃSKA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='PARMEŃSKA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='PARMEŃSKA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='PARMEŃSKA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='Z GRUSZKĄ'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='Z GRUSZKĄ'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='Z GRUSZKĄ'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='Z GRUSZKĄ'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='FAMILIJNA'), (select id from rozmiary where nazwa='30 cm'), 43.50),
  ((select id from produkty where nazwa='FAMILIJNA'), (select id from rozmiary where nazwa='40 cm'), 67.50),
  ((select id from produkty where nazwa='FAMILIJNA'), (select id from rozmiary where nazwa='50 cm'), 85.00),
  ((select id from produkty where nazwa='FAMILIJNA'), (select id from rozmiary where nazwa='60 cm'), 105.50),
  ((select id from produkty where nazwa='SEROWA'), (select id from rozmiary where nazwa='30 cm'), 43.50),
  ((select id from produkty where nazwa='SEROWA'), (select id from rozmiary where nazwa='40 cm'), 67.50),
  ((select id from produkty where nazwa='SEROWA'), (select id from rozmiary where nazwa='50 cm'), 85.00),
  ((select id from produkty where nazwa='SEROWA'), (select id from rozmiary where nazwa='60 cm'), 105.50),
  ((select id from produkty where nazwa='VEGE-MARGHERITA'), (select id from rozmiary where nazwa='30 cm'), 30.50),
  ((select id from produkty where nazwa='VEGE-MARGHERITA'), (select id from rozmiary where nazwa='40 cm'), 48.50),
  ((select id from produkty where nazwa='VEGE-MARGHERITA'), (select id from rozmiary where nazwa='50 cm'), 64.00),
  ((select id from produkty where nazwa='VEGE-MARGHERITA'), (select id from rozmiary where nazwa='60 cm'), 75.50),
  ((select id from produkty where nazwa='VEGE-RUCOLA'), (select id from rozmiary where nazwa='30 cm'), 42.00),
  ((select id from produkty where nazwa='VEGE-RUCOLA'), (select id from rozmiary where nazwa='40 cm'), 63.50),
  ((select id from produkty where nazwa='VEGE-RUCOLA'), (select id from rozmiary where nazwa='50 cm'), 79.00),
  ((select id from produkty where nazwa='VEGE-RUCOLA'), (select id from rozmiary where nazwa='60 cm'), 98.00),
  ((select id from produkty where nazwa='TWOJA PIZZA'), (select id from rozmiary where nazwa='30 cm'), 30.50),
  ((select id from produkty where nazwa='TWOJA PIZZA'), (select id from rozmiary where nazwa='40 cm'), 48.50),
  ((select id from produkty where nazwa='TWOJA PIZZA'), (select id from rozmiary where nazwa='50 cm'), 64.00),
  ((select id from produkty where nazwa='TWOJA PIZZA'), (select id from rozmiary where nazwa='60 cm'), 75.50)
on conflict do nothing;

insert into produkty (kategoria_id, nazwa, opis, cena, kolejnosc) values
  ((select id from kategorie where nazwa='Zestawy'), 'PARTY BOX', '60 cm Kebab Pizza, 60 cm Clasic, 60 cm Chłopska + 9 sosów gratis', 260.00, 1),
  ((select id from kategorie where nazwa='Zestawy'), 'MINI PARTY BOX', '50 cm Clasic, 50 cm Kebab Pizza, 50 cm Chłopska + 6 dowolnych sosów', 210.00, 2),
  ((select id from kategorie where nazwa='Zestawy'), 'FAMILY BOX', '40 cm Familijna, 40 cm Clasic, 40 cm Kebab Pizza + 3 sosy gratis', 175.00, 3),
  ((select id from kategorie where nazwa='Zestawy'), 'KINDER BOX', '40 cm Margherita z szynką, 40 cm Margherita z pieczarkami, 40 cm Margherita z dodatkowym serem + 3 sosy gratis', 145.00, 4),
  ((select id from kategorie where nazwa='Promocje'), '2× MARGHERITA 60 CM', 'Dwie Margherity 60 cm', 120.00, 1),
  ((select id from kategorie where nazwa='Promocje'), 'MARGHERITA 60 CM + PEPSI 0,85 L', 'Margherita 60 cm, 2× sos czosnkowy, Pepsi 0,85 l', 75.00, 2),
  ((select id from kategorie where nazwa='Napoje'), 'PEPSI 0,85 L', '', 11.00, 1),
  ((select id from kategorie where nazwa='Napoje'), 'PEPSI ZERO CUKRU 0,85 L', '', 11.55, 2),
  ((select id from kategorie where nazwa='Napoje'), 'PEPSI 0,5 L', '', 7.00, 3),
  ((select id from kategorie where nazwa='Napoje'), 'PEPSI ZERO CUKRU 0,5 L', '', 7.00, 4),
  ((select id from kategorie where nazwa='Napoje'), '7UP 0,5 L', '', 7.00, 5),
  ((select id from kategorie where nazwa='Napoje'), 'MIRINDA 0,5 L', '', 7.00, 6),
  ((select id from kategorie where nazwa='Napoje'), 'LIPTON BRZOSKWINIA 0,5 L', '', 7.00, 7),
  ((select id from kategorie where nazwa='Napoje'), 'WODA NIEGAZOWANA 0,5 L', '', 7.00, 8),
  ((select id from kategorie where nazwa='Sosy'), 'SOS CZOSNKOWY', '', 3.50, 1),
  ((select id from kategorie where nazwa='Sosy'), 'SOS POMIDOROWY', '', 3.50, 2),
  ((select id from kategorie where nazwa='Sosy'), 'KETCHUP ŁAGODNY', '', 3.50, 3),
  ((select id from kategorie where nazwa='Sosy'), 'SOS JALAPENO', '', 3.50, 4),
  ((select id from kategorie where nazwa='Sosy'), 'SOS BBQ', '', 3.50, 5),
  ((select id from kategorie where nazwa='Sosy'), 'SOS ZIOŁOWY', '', 3.50, 6)
on conflict do nothing;

insert into dodatki_grupy (nazwa, cena, kolejnosc) values
  ('Mięsne', 4.50, 1),
  ('Sery', 6.00, 2),
  ('Warzywa i owoce', 3.00, 3),
  ('Sosy', 3.50, 4),
  ('Bez dopłaty', 0.00, 5)
on conflict do nothing;
insert into dodatki (grupa_id, nazwa, kolejnosc) values
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'mięso mielone', 1),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'salami', 2),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'szynka', 3),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'boczek', 4),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'polędwica', 5),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'tuńczyk', 6),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'krewetki', 7),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'anchois', 8),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'kabanosy', 9),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'łosoś wędzony', 10),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'kurczak panierowany', 11),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'kebab drobiowy', 12),
  ((select id from dodatki_grupy where nazwa='Mięsne'), 'frankfurterki', 13),
  ((select id from dodatki_grupy where nazwa='Sery'), 'dodatkowy ser', 1),
  ((select id from dodatki_grupy where nazwa='Sery'), 'ser feta', 2),
  ((select id from dodatki_grupy where nazwa='Sery'), 'ser lazur', 3),
  ((select id from dodatki_grupy where nazwa='Sery'), 'ser camembert', 4),
  ((select id from dodatki_grupy where nazwa='Sery'), 'ser wędzony', 5),
  ((select id from dodatki_grupy where nazwa='Sery'), 'ser philadelphia', 6),
  ((select id from dodatki_grupy where nazwa='Sery'), 'ser favita', 7),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'pieczarki', 1),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'cebula', 2),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'świeży ogórek', 3),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'ogórek konserwowy', 4),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'papryka konserwowa', 5),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'papryka świeża', 6),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'papryka jalapeno', 7),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'pomidor', 8),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'pomidory suszone', 9),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'kukurydza', 10),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'kolby kukurydzy', 11),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'oliwki zielone', 12),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'groszek', 13),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'fasola czerwona', 14),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'szpinak', 15),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'brokuły', 16),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'szparagi', 17),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'kapary', 18),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'rukola', 19),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'ziemniaki', 20),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'czosnek', 21),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'jajko', 22),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'ananas', 23),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'gruszka', 24),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'żurawina', 25),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'orzech włoski', 26),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'miód', 27),
  ((select id from dodatki_grupy where nazwa='Warzywa i owoce'), 'liście nori', 28),
  ((select id from dodatki_grupy where nazwa='Sosy'), 'ketchup', 1),
  ((select id from dodatki_grupy where nazwa='Sosy'), 'sos czosnkowy', 2),
  ((select id from dodatki_grupy where nazwa='Sosy'), 'sos ziołowy', 3),
  ((select id from dodatki_grupy where nazwa='Sosy'), 'sos bbq', 4),
  ((select id from dodatki_grupy where nazwa='Sosy'), 'sos jalapeno', 5),
  ((select id from dodatki_grupy where nazwa='Bez dopłaty'), 'sos śmietanowy zamiast pomidorowego', 1),
  ((select id from dodatki_grupy where nazwa='Bez dopłaty'), 'oregano', 2),
  ((select id from dodatki_grupy where nazwa='Bez dopłaty'), 'bazylia', 3),
  ((select id from dodatki_grupy where nazwa='Bez dopłaty'), 'pieprz', 4)
on conflict do nothing;

insert into sosy_gratis (nazwa, kolejnosc) values ('ketchup',1),('sos czosnkowy',2),('sos ziołowy',3),('sos bbq',4),('sos jalapeno',5) on conflict do nothing;

-- Strefy: przepisane z Appinetu (36 z 45 – 9 pozycji panel nie pokazał). Kody pocztowe 1:1 z Appinetu.
-- Przypisanie Ostrów/Kalisz wg położenia – sprawdź w panelu admina.
insert into strefy (lokal_id, miejscowosc, kod, oplata) values
  (5, 'Ostrów Wielkopolski', '63-400', 0.00),
  (5, 'Zacharzew', '63-400', 10.00),
  (5, 'Stary Staw', '63-410', 10.00),
  (5, 'Lewkowiec', '63-410', 10.00),
  (5, 'Wtórek', '63-400', 10.00),
  (5, 'Topola Mała', '63-400', 10.00),
  (5, 'Lamki', '63-400', 15.00),
  (5, 'Gorzyce Wielkie', '63-410', 15.00),
  (5, 'Franklinów', '63-410', 15.00),
  (5, 'Radłów', '63-440', 15.00),
  (5, 'Karski', '63-410', 15.00),
  (5, 'Czekanów', '63-410', 15.00),
  (5, 'Kołątajew', '63-410', 15.00),
  (5, 'Smardowskie Olendry', '63-400', 15.00),
  (5, 'Nowe Skalmierzyce', '63-400', 15.00),
  (5, 'Wysocko Wielkie', '63-421', 15.00),
  (5, 'Wysocko Małe', '63-421', 15.00),
  (5, 'Boczków', '63-460', 15.00),
  (5, 'Mączniki', '63-460', 15.00),
  (5, 'Lewków', '63-410', 20.00),
  (5, 'Topola Wielka', '63-421', 20.00),
  (5, 'Janków Przygodzki', '63-421', 20.00),
  (5, 'Przygodzice', '63-421', 20.00),
  (5, 'Parczew', '63-405', 25.00),
  (5, 'Sadowie', '63-400', 25.00),
  (5, 'Ociąż', '63-460', 30.00),
  (5, 'Sieroszewice', '63-405', 30.00),
  (2, 'Kalisz', '62-800', 0.00),
  (2, 'Borków Stary', '62-817', 15.00),
  (2, 'Czajków', '63-812', 15.00),
  (2, 'Czartki', '63-817', 15.00),
  (2, 'Dębe', '62-817', 15.00),
  (2, 'Florentyna', '62-817', 15.00),
  (2, 'Koronka', '62-817', 15.00),
  (2, 'Kamień-Kolonia', '62-834', 20.00)
on conflict do nothing;

insert into ustawienia (klucz, wartosc, opis) values
  ('min_zamowienie', '45', 'Minimalna wartość produktów (zł)'),
  ('platnosc_online', 'true', 'Autopay'),
  ('platnosc_gotowka', 'false', 'Gotówka przy odbiorze'),
  ('platnosc_karta', 'false', 'Karta przy odbiorze'),
  ('zamawianie_wylaczone', 'false', 'Wyłącza przyjmowanie zamówień'),
  ('komunikat', '""', 'Pasek informacyjny na stronie'),
  ('czas_dostawy_min', '60', 'Szacowany czas dostawy (min)'),
  ('czas_odbioru_min', '30', 'Szacowany czas do odbioru (min)'),
  ('regulamin_url', '"https://coolpizza.pl/content/regulamin"', 'Link do regulaminu'),
  ('polityka_url', '"https://coolpizza.pl/content/polityka-prywatnosci"', 'Link do polityki prywatności')
on conflict (klucz) do nothing;
commit;
